# Generated by Django 5.0.6 on 2024-06-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('ta', 'TA'), ('professor', 'Professor')], default='student', max_length=10),
        ),
    ]
